multipass: true

plugins:
  - cleanupAttrs: true
  - inlineStyles: true
  - removeDoctype: true
  - removeXMLProcInst: true
  - removeComments: true
  - removeMetadata: true
  - removeTitle: true
  - removeDesc: true
  - removeUselessDefs: true
  - removeEditorsNSData: true
  - removeEmptyAttrs: true
  - removeHiddenElems: true
  - removeEmptyText: true
  - removeEmptyContainers: true
  - removeViewBox: false
  - cleanUpEnableBackground: true
  - convertStyleToAttrs: true
  - convertColors: true
  - convertPathData: true
  - convertTransform: false
  - removeUnknownsAndDefaults: true
  - removeNonInheritableGroupAttrs: true
  - removeUselessStrokeAndFill: true
  - removeUnusedNS: true
  - cleanupIDs: true
  - cleanupNumericValues:
      floatPrecision: 2
  - moveElemsAttrsToGroup: true
  - moveGroupAttrsToElems: true
  - collapseGroups: true
  - removeRasterImages: false
  - mergePaths: true
  - convertShapeToPath: true
  - sortAttrs: false
  - removeDimensions: true
  - removeAttrs:
      attrs:
        - '(fill.*|stroke.*)'
