variables:
  CI: true

jobs:
  - job: code_validation_and_tests
    displayName: Code validation and tests
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      maxParallel: 3
      matrix:
        node_12_x:
          node_version: 12.x
        node_10_x:
          node_version: 10.x
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: 'Install Node.js $(node_version)'
      - script: npm install -g npm@latest
        displayName: 'Install latest NPM'
      - script: |
          npm ci --prefer-offline --no-audit
          npm run deps:check
        displayName: 'Install and check NPM deps'
      - script: |
          # npm run typecheck
          npm run lint
          npm test
        displayName: 'Check code and run tests'

  - job: release_packages
    displayName: Release packages
    dependsOn:
      - code_validation_and_tests
    condition: and(succeeded(), or(eq(variables['Build.SourceBranchName'], 'master'), eq(variables['Build.SourceBranchName'], 'next')), ne(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - checkout: self
        clean: true
      # By default Azure Pipelines do checkouts of specific commits (detached HEAD)
      # and we need to be at master to be able to push version bump changes
      - script: git checkout $(Build.SourceBranchName)
        displayName: 'Checkout branch'
      - script: |
          git config --global user.email "no-reply@azure.com"
          git config --global user.name "Azure DevOps Pipeline"
          git remote set-url origin https://$(GH_TOKEN)@github.com/PowelAS/design-primitives.git
        displayName: 'Configure git'
      - task: NodeTool@0
        inputs:
          versionSpec: 10
        displayName: 'Install Node.js 10'
      - script: |
          set -e
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y libstdc++-4.9-dev
        displayName: 'Install libstdc++ needed for nodegit'
      - script: echo "//registry.npmjs.org/:_authToken=$(NPM_TOKEN)" > ~/.npmrc
        displayName: 'Create .npmrc'
      - script: |
          npm ci --prefer-offline --no-audit
          npm install --no-save nodegit@0.27.0
        displayName: 'Install NPM deps'
      - script: npm run release -- --no-parallel --print-release
        displayName: 'Publish all packages to NPM'
        env:
          GH_TOKEN: $(GH_TOKEN)
